name: ä¸‰æ¶ˆæœºå™¨äººæœåŠ¡éƒ¨ç½²
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Environment to deploy.(Select:dev,pre,production,dev1)'
        required: true
        default: 'dev'
jobs:
  deploy-dev:
    name: Deploy robot-dev
    runs-on: [ robot-dev ]
    if: ${{ github.event.inputs.job == 'dev'}}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: æ‹‰å–gité…ç½®
        run: bash deploy/pull_config.sh dev

      - name: ç¼–è¯‘é•œåƒ 
        run: docker-compose -f deploy/docker-compose-dev.yaml build

      - run: docker-compose -f deploy/docker-compose-dev.yaml stop
      - run: docker-compose -f deploy/docker-compose-dev.yaml up -d

      - name: æŸ¥çœ‹æœåŠ¡çŠ¶æ€
        run: docker-compose -f deploy/docker-compose-dev.yaml logs | tail -n 20

      - run: echo "ğŸ This job's status is ${{ job.status }}."
