name: matching-story-robot-service-deploy
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Environment to deploy.(Select:dev,pre,prod)'
        required: true
        default: 'dev'
      csv_version:
        description: 'Csv config version: use latest is empty'
        required: false
        default: ''

jobs:
  deploy-dev:
    name: Deploy robot-dev
    runs-on: [ robot-dev ]
    if: ${{ github.event.inputs.job == 'dev'}}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: dev
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: æ‹‰å–gité…ç½®
        run: bash deploy/pull_config.sh dev ${{ github.event.inputs.csv_version }}

      - name: ç¼–è¯‘é•œåƒ 
        run: docker-compose -f deploy/docker-compose-dev.yaml build

      - run: docker-compose -f deploy/docker-compose-dev.yaml stop
      - run: docker-compose -f deploy/docker-compose-dev.yaml up -d

      - name: æŸ¥çœ‹æœåŠ¡çŠ¶æ€
        run: docker-compose -f deploy/docker-compose-dev.yaml logs | tail -n 20

      - run: echo "ğŸ This job's status is ${{ job.status }}."
  deploy-pre:
    name: Deploy robot-pre
    runs-on: [ robot-pre ]
    if: ${{ github.event.inputs.job == 'pre'}}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: pre
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: æ‹‰å–gité…ç½®
        run: bash deploy/pull_config.sh dev ${{ github.event.inputs.csv_version }}

      - name: ç¼–è¯‘é•œåƒ 
        run: docker-compose -f deploy/docker-compose-pre.yaml build

      - run: docker-compose -f deploy/docker-compose-pre.yaml stop
      - run: docker-compose -f deploy/docker-compose-pre.yaml up -d

      - name: æŸ¥çœ‹æœåŠ¡çŠ¶æ€
        run: docker-compose -f deploy/docker-compose-pre.yaml logs | tail -n 20

      - run: echo "ğŸ This job's status is ${{ job.status }}."
  deploy-prod:
    name: Deploy robot-prod
    runs-on: [ robot-prod ]
    if: ${{ github.event.inputs.job == 'prod'}}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: æ‹‰å–gité…ç½®
        run: bash deploy/pull_config.sh master  ${{ github.event.inputs.csv_version }}

      - name: ç¼–è¯‘é•œåƒ 
        run: docker-compose -f deploy/docker-compose-prod.yaml build

      - run: docker-compose -f deploy/docker-compose-prod.yaml stop
      - run: docker-compose -f deploy/docker-compose-prod.yaml up -d

      - name: æŸ¥çœ‹æœåŠ¡çŠ¶æ€
        run: docker-compose -f deploy/docker-compose-prod.yaml logs | tail -n 20

      - run: echo "ğŸ This job's status is ${{ job.status }}."
